#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r
# * covr: https://github.com/jimhester/covr
#
# Validate your .travis.yml file at http://lint.travis-ci.org/
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
r_check_args: --as-cran
latex: false

matrix:
  include:
#    - os: linux
#      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
#    - os: osx
#      r: oldrel
    - os: osx
      r: release

before_install:
  - Rscript -e 'c(physical = parallel::detectCores(logical = FALSE), logical = parallel::detectCores())'
  - export _R_CHECK_TIMINGS_=0


notifications:
  email:
    on_success: change
    on_failure: change
