#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r
#
# YAML validated using http://www.yamllint.com/
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
r_check_args: --as-cran
latex: false

matrix:
  include:
#    - os: linux
#      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
#    - os: osx
#      r: oldrel
    - os: osx
      r: release
    - os: linux
      r: release
      script:
        - R CMD build --no-build-vignettes --no-manual .
        - R CMD INSTALL --no-docs --no-html --no-help --no-demo *.tar.gz
        - Rscript -e "future.tests::check" --args --test-plan=sequential
      env: NB='sequential'
##    - os: linux
##      r: release
##      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
##      after_success:
##        - Rscript -e "future.tests::check" --args --test-plan=multicore
##      env: NB='multicore'
##    - os: linux
##      r: release
##      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
##      after_success:
##        - Rscript -e "future.tests::check" --args --test-plan=multisession
##      env: NB='multisession'
##    - os: linux
##      r: release
##      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
##      after_success:
##        - Rscript -e "future.tests::check" --args --test-plan=cluster
##      env: NB='cluster'

before_install:
  - Rscript -e 'c(physical = parallel::detectCores(logical = FALSE), logical = parallel::detectCores())'
  - export _R_CHECK_TIMINGS_=0


notifications:
  email:
    on_success: change
    on_failure: change
